// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: token
func (_m *Connector) Authorize(token string) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: postcode
func (_m *Connector) Find(postcode string) (interface{}, error) {
	ret := _m.Called(postcode)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(postcode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(postcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewConnectorT interface {
	mock.TestingT
	Cleanup(func())
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConnector(t NewConnectorT) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
